# Generated by Django 4.0.1 on 2023-04-28 16:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_member_id_roommember_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommember',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('75206cf9-97d8-43fd-aa77-ba9f6ab33ac1')),
        ),
    ]
