# Generated by Django 4.0.1 on 2023-04-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_roommember_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='uid',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
